// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPqFwO7qEMYU5JdwbMC0CGZOoO5h-0JIg',
    appId: '1:176414956571:web:01e27cc47791e8313f6cbe',
    messagingSenderId: '176414956571',
    projectId: 'zoomclone-deeb0',
    authDomain: 'zoomclone-deeb0.firebaseapp.com',
    storageBucket: 'zoomclone-deeb0.appspot.com',
    measurementId: 'G-5TWEGNYVHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6ekLrqmJZlma3q6Fz4dO41dPZoOGnAVU',
    appId: '1:176414956571:android:a0c00339ac836a823f6cbe',
    messagingSenderId: '176414956571',
    projectId: 'zoomclone-deeb0',
    storageBucket: 'zoomclone-deeb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbk_O0oOGZuDnyF-JQaDrzu3xrkkRN6uc',
    appId: '1:176414956571:ios:5f3ff4d3930418013f6cbe',
    messagingSenderId: '176414956571',
    projectId: 'zoomclone-deeb0',
    storageBucket: 'zoomclone-deeb0.appspot.com',
    androidClientId: '176414956571-oppdngom1af6v28phtp40s3cm6dcdits.apps.googleusercontent.com',
    iosClientId: '176414956571-o4vj8c18il7amjkbblbuhge22oqgos2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkstream',
  );
}
